source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
workspace 'MyFacebookImagePicker-iOS'

target 'FacebookImagePicker' do

pod 'FBSDKCoreKit', '~> 5.1.1'
pod 'FBSDKLoginKit', '~> 5.1.1'

end
